import "./globals.css";
import { Inter } from "next/font/google";
import { Metadata } from "next";

  export const metadata={
    title:'PKG-FORUM',
    discription:'Generated by next.js'
  }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
