// import "./globals.css";
// import { Inter } from "next/font/google";
// import SessionWrapper from "./SessionWrapper";
// // import Navbar from '@/app/(components)/navbar/page';
// // import Sidebar from '@/app/(components)/sidebar/page';

// export const metadata = {
//   title: "PKG-FORUM",
//   description: "Generated by next.js",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@400;500;700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body>
//         <SessionWrapper>
          
//           {children}</SessionWrapper>
//       </body>
//     </html>
//   );
// }


// app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";
import SessionWrapper from "./SessionWrapper";
import NavBar from "@/app/(components)/navbar";
import Sidebar from "@/app/(components)/sidebar";

export const metadata = {
  title: "PKG-FORUM",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <SessionWrapper>
          <div className="bg-[#15161A] min-h-screen text-gray-300">
            <NavBar />
            <div className="flex">
              <Sidebar />
              <main className="flex-1 p-10 py-4">{children}</main>
            </div>
          </div>
        </SessionWrapper>
      </body>
    </html>
  );
}
