import "./globals.css";
import { Inter } from "next/font/google";
import SessionWrapper from "./SessionWrapper";
import NavBar from "@/app/(mainComponents)/navbar";
import Sidebar from "@/app/(mainComponents)/sidebar";
import { store } from "@/core/redux/store";
import Provider from "@/core/redux/provider";

export const metadata = {
  title: "PKG-FORUM",
  description: "Generated by next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Martian+Mono:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <SessionWrapper>
          <div className="bg-[#15161A] min-h-screen text-gray-300">
            <NavBar />
            <div className="flex1 flex ">
              <Sidebar />
              <Provider>
                <div className="p-10 w-full -mr-6">{children}</div>
              </Provider>
            </div>
          </div>
        </SessionWrapper>
      </body>
    </html>
  );
}
